# Generated by Django 3.2.13 on 2022-04-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bandwidth_quantity', models.IntegerField()),
                ('bandwidth_unit', models.CharField(choices=[('Mbps', 'Mbps'), ('Gbps', 'Gbps')], max_length=4)),
            ],
        ),
    ]
