# Generated by Django 3.2.13 on 2022-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.IntegerField(choices=[(0, 'Wireless'), (1, 'Fibra óptica')], default=0),
        ),
    ]
