# Generated by Django 3.2.13 on 2022-05-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.IntegerField(choices=[(0, 'Inalámbrico'), (1, 'Fibra óptica')], default=0),
        ),
    ]
