# Generated by Django 3.2.13 on 2022-05-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['type', 'price']},
        ),
        migrations.RenameField(
            model_name='package',
            old_name='bandwidth_quantity',
            new_name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='package',
            name='bandwidth_unit',
        ),
    ]
