# Generated by Django 3.2.13 on 2022-05-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20220502_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='bandwidth',
            new_name='speed_in_mbps',
        ),
    ]
