# Generated by Django 3.2.13 on 2022-05-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_rename_bandwidth_package_speed_in_mbps'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('type', 'speed_in_mbps')},
        ),
    ]
