# Generated by Django 3.2.13 on 2022-04-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.RemoveField(
            model_name='quote',
            name='location',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='quote',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.address'),
        ),
    ]
