# Generated by Django 3.2.13 on 2022-04-29 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20220429_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.address'),
        ),
    ]
