# Generated by Django 3.2.13 on 2022-05-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_unique_together'),
        ('quotes', '0004_auto_20220516_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=30, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=50, verbose_name='Calle y número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.address'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package', verbose_name='Paquete'),
        ),
    ]
